# Generated by Django 6.0 on 2026-01-03 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 13, 53, 22, 258749, tzinfo=datetime.timezone.utc)),
        ),
    ]
