# Generated by Django 6.0 on 2026-01-03 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_emailotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 15, 26, 29, 731215, tzinfo=datetime.timezone.utc)),
        ),
    ]
