# Generated by Django 6.0 on 2026-01-03 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_emailotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 16, 2, 55, 634554, tzinfo=datetime.timezone.utc)),
        ),
    ]
