# Generated by Django 6.0 on 2026-01-03 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_emailotp_expires_at_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 17, 3, 8, 940645, tzinfo=datetime.timezone.utc)),
        ),
    ]
