# Generated by Django 6.0 on 2026-01-04 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_emailotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 13, 37, 19, 143423, tzinfo=datetime.timezone.utc)),
        ),
    ]
